version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: users
      POSTGRES_PASSWORD: password
    ports:
      - "10000:5432"

  auth:
    build: /authd

  api:
    build: /api

  app:
    build: /app

