version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: users
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "6543:5432"

  auth:
    depends_on:
      - db
    build: auth
    environment:
      PYTHONPATH: /usr/src
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      ACCESS_TOKEN_EXPIRE_HOURSE: 720
    ports:
      - "1000:1000"

  api:
    depends_on:
      - db
    build: api
    environment:
      PYTHONPATH: /usr/src
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      TELEGRAM_API_KEY: "${TELEGRAM_API_KEY}"
      VK_API_KEY: "${VK_API_KEY}"
      LOGS_PATH: /usr/src/api/logs
    ports:
      - "1001:1001"
    volumes:
      - ./logs:/usr/src/api/logs

  app:
    depends_on:
      - db
    build: app
    environment:
      HOST_DOMAIN: "${HOST_DOMAIN}"
      PYTHONPATH: /usr/src
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      SECRET_KEY: "${SECRET_KEY}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
    ports:
      - "1002:1002"

volumes:
  api_logs: